name: Create Issue on Push

on:
  push:
    branches: [main] # Replace with the branch you want to trigger the workflow on

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create issue
      run: |
        git config --global user.email "malsef.maks@yandex.ru" # Replace with your email address
        git config --global user.name "Nyorikenoichi" # Replace with your name
        issue_title="New Push to Main Branch"
        issue_body="A new push has been made to the main branch.

        Commit SHA: ${{ github.sha }}

        Commit message: ${{ github.event.head_commit.message }}

        Pusher: ${{ github.event.pusher.name }}

        Repository: ${{ github.repository }}

        View the workflow run at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }} for more information."

        "The 'generate' job failed. See details at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/issues" \
        -d "{\"title\":\"$issue_title\",\"body\":\"$issue_body\"}"
