name: Create Issue on Push

on:
  push:
    branches: [ "main" ] # Replace with the branch you want to trigger the workflow on

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create issue
      run: |
        issue_title="New Push to Main Branch"
        issue_body="A new push has been made to the main branch.

        Commit SHA: ${{ github.sha }}

        Commit message: ${{ github.event.head_commit.message }}

        Pusher: ${{ github.event.pusher.name }}

        Repository: ${{ github.repository }}

        View the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }}) for more information."

        gh issue create --title "$issue_title" --body "$issue_body" --repo ${{ github.repository }} --assignee ${{ github.actor }}
